---
title: "Capstone Project"
author: "Roderick Fan"
date: "2023-03-29"
output: html_document
---

Clean Environment
Loading Packages, dataset
```{r}
rm(list = ls())
cat("\14")
library(tidyverse)
library(here)
library(lubridate)
library(lme4)
library(randomForest)
library(caret)
library(rpart)
library(rpart.plot)
library(car)
spot <- read.csv(here("Spot Data.csv"))
```

Preprocessing
```{r}
#Rename Patient ID
spot$Patient.ID <- as.numeric(factor(spot$Patient.ID, levels=unique(spot$Patient.ID)))

#Binomial Sex
spot$Patient.Sex <- as.factor(spot$Patient.Sex)

#Dropping Redundant Predictors   
spot <- spot[,-c(5)]

#Factoring Specimen Type
spot$Specimen.Type <- as.factor(spot$Specimen.Type)

#Factoring and Renaming Client Location
spot$Client.ID <- as.factor(spot$Client.ID)
levels(spot$Client.ID) <- c("Location A","Location B","Location C","Location D","Location E","Location F",
                            "Location G","Location H","Location I","Location J","Location K","Location L",
                            "Location M","Location N","Location O","Location P","Location Q","Location R")


#Convert and Simplify Datetime Columns
datetime_cols <- c("Datetime.Kit.Delivered", "Datetime.Kit.Registered", "Datetime.Sample.Sent.In", "Datetime.Sample.Received", "Datetime.of.End.Status")
for (col in datetime_cols) {
  spot[[col]] <- as.Date(substr(spot[[col]], 1, 10), format="%Y-%m-%d")
}
```


Customer Age Distribution
```{r}
ggplot(spot, aes(x =spot$Patient.Age, fill = Patient.Sex)) +
  geom_histogram(color = "black", alpha = 0.5, binwidth = 5) +
  theme_classic()+
  scale_x_continuous(breaks = seq(15, 90, by = 5))+
  labs(title = "Age Distribution of Patients",
       x = "Patient Age",
       y = "Count")
```


Geographical Information of Kits Delivery
```{r}
# Tableau
```


calculate time gap and visualize the distribution of time gap
```{r}
#Calculate Time Gap between Sent in and Resulted
spot$time.gap1 <- as.numeric(difftime(spot$Datetime.Sample.Sent.In, spot$Datetime.Kit.Delivered,units = "day"))
spot$time.gap2 <- as.numeric(difftime(spot$Datetime.of.End.Status, spot$Datetime.Sample.Sent.In,units = "day"))
t(t(colnames(spot)))

spot.clean <- spot[,-c(7:11)]
spot.clean <- na.omit(spot.clean)
spot.clean$End.Status[spot.clean$End.Status == "partially_resulted"] <- "resulted"
spot.clean$End.Status[spot.clean$End.Status %in% c("collected", "collection_exception","delivered","delivery_exception","received")] <- "rejected"

threshold.1 <-  1.5*(IQR(spot.clean$time.gap1))
outliers.1 <- spot.clean$time.gap1 < median(spot.clean$time.gap1) - threshold.1 | spot.clean$time.gap1 > median(spot.clean$time.gap1) + threshold.1
spot.gap.1 <- spot.clean[!outliers.1,]

threshold.2 <-  1.5*(IQR(spot.clean$time.gap2))
outliers.2 <- spot.clean$time.gap2 < median(spot.clean$time.gap2) - threshold.2 | spot.clean$time.gap2 > median(spot.clean$time.gap2) + threshold.2
spot.gap.2 <- spot.clean[!outliers.2,]

box.gap.1 <- ggplot(data = spot.gap.1)+
                geom_boxplot(aes(x = Patient.Sex, y = time.gap1, fill = Patient.Sex), alpha = 0.5)+
                coord_flip()+
                theme_classic()

box.gap.2 <- ggplot(data = spot.gap.2)+
                geom_boxplot(aes(x = Patient.Sex, y = time.gap2, fill = Patient.Sex), alpha = 0.5)+
                coord_flip()+
                theme_classic()
```

visualize the Distribution of Number of Tests Taken by Patients
```{r}
test.duration <- spot%>%
  count(Patient.ID) 

test.duration$n <- as.factor(test.duration$n)
test.duration <- test.duration[!is.na(test.duration$n),]

ggplot(test.duration, aes(x = n)) +
  geom_bar(alpha = 0.5, color = "black", fill = "lightblue") +
  geom_text(stat = "count", aes(label = after_stat(count)), hjust = -0.5) +
  ylim(0,3500)+
  coord_flip()+
  labs(x = "Number of Tests Taken", 
       y = "Count",
       title ="Distribution of Number of Tests Taken by Patients") +
  theme_classic()

```


Visualization of Success Rate and Count by Specimen Type
```{r}
test.rate <- spot.clean%>%
  group_by(Specimen.Type) %>%
  summarize(Count = n(), resulted_rate = sum(End.Status == "resulted")/n())

ggplot(test.rate, aes(x = reorder(Specimen.Type,Count), y = resulted_rate, fill = Specimen.Type)) +
  geom_bar(aes(y = Count),stat = "identity", alpha = 0.5, width = 0.5) +
  geom_text(aes(label = paste0(Count, " / ",round(resulted_rate*100,2), "%"), y = Count + 1), 
            color = "black", fontface = "bold", size = 4, hjust = -0.1) +
  labs(x = "", y = "Test times (with Success Rate)", 
       title = "Success Rate and Count by Specimen Type") +
  scale_fill_discrete(name = "Specimen Type") +
  scale_y_continuous(sec.axis = sec_axis(~./max(test.rate$count), name = "Count"))+
  ylim(0,8000)+
  coord_flip()+
  theme_classic()+
  theme(legend.position = "none")

```




Model Build: Random Forest
```{r}
set.seed(111)
t(t(colnames(spot.clean)))
# partition
set.seed(1)
spot.df <- spot.clean[,-c(1,2,8,10)]
train.index <- sample(c(1:dim(spot.df)[1]), dim(spot.df)[1]*0.6)
train <- spot.df[train.index,]
valid <- spot.df[-train.index,]

# random forest
spot.rf <- randomForest(as.factor(End.Status) ~ ., data = spot.df, ntree = 100, mtry=4, nosize=5, importance=TRUE)

varImpPlot(spot.rf, type=1)
spot.rf.pred <- predict(spot.rf, valid)
confusionMatrix(spot.rf.pred, as.factor(valid$End.Status), positive = "resulted")

```

Decision Tree
```{r}
#Set Decision Tree Data set
tree.df <- spot.clean
tree.df$Patient.Sex <- ifelse(tree.df$Patient.Sex == "M",1,0)
tree.df$End.Status <- ifelse(tree.df$End.Status == "resulted", 1, 0)

#Turn Categorical Variable into Dummy Variable
tree.dummy <- predict(dummyVars(~ Specimen.Type + Client.ID, tree.df), newdata = tree.df)
tree.df <- tree.df[,-c(5,6)]
tree.df <- cbind(tree.df,tree.dummy)

model <- rpart(as.factor(End.Status) ~ . - Rejection.Reason - Patient.ID - Patient.Zip, data = tree.df)

rpart.plot(model)
```


```{r}
spot.df$End.Status <- ifelse(spot.df$End.Status == "resulted", 1, 0)
cor(spot.df[,-c(3:5)])

train.index.m <- sample(c(1:dim(spot.df)[1]), dim(spot.df)[1]*0.6)
train.mix <- spot.df[train.index.m,]
valid.mix <- spot.df[-train.index.m,]

mixed.model <- glmer(End.Status ~   (1 | Specimen.Type)
                                  +  time.gap1
                                  +  time.gap2,
                     data = train.mix,
                     family = binomial())

plot(mixed.model)
test_predictions <- predict(mixed.model, newdata = valid.mix, type = "response")
test_predictions_binary <- ifelse(test_predictions > 0.8, 1, 0)
confusionMatrix(table(test_predictions_binary, valid.mix$End.Status), positive = "1")
```






